### ISSUE TITLE
NCIT Sex

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#175] opened 2023-05-09 14:39 UTC
The Sex field is showing the NCIT ontlogy terms for male, female, etc., but the Phenopacket standard uses an enumeration and not ontology terms. Please remove the ontology term and just show Male, Female, Unknown, Other

**Comment by belkassaby** [comment] 2023-05-23 20:29
Fixed in [71a131](https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/179/commits/71a131a45b222a3197bcda10469f5d26fab5ced2)

**Comment by BethSundberg** [comment] 2023-06-14 13:04
@belkassaby Has this fix been merged to sqa? This is what I am getting when I start a phenopacket. 


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/1e48eb34-22ce-4348-b958-40e5077e731d)

**Comment by belkassaby** [comment] 2023-06-14 14:50
This is weird... here is a screenshot of the sqa instance on firefox for me: 

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/1378819/466de380-9844-4732-b820-98bafb7a59d5)

**Comment by pnrobinson** [comment] 2023-06-14 14:55
PS: The Sex field is just an enum and does not map to anything else! Please remove the tool tip!

**Comment by BethSundberg** [comment] 2023-06-14 14:56
@belkassaby The problem is that I can't do a hard refresh of my Firefox. I also noted that it is not showing the new version number.

**Comment by BethSundberg** [comment] 2023-06-14 15:07
@belkassaby I managed to clear out my Firefox history and it is working fine now for the sex field. I will mark this done and put in a new bug to get the tool tip removed per Peter's comment.

**Closed** 2023-06-27 23:22 UTC
